### ISSUE TITLE
"None Standard Issue" is buggy with the game's introduction

### ISSUE THREAD

**Issue by Flrys** [Milkman68/HL2-RebalanceMod#4]
The stun batons being replaced by SMGs/pistols can make for some buggy sequences where the metropolice will attempt to hit you but won't be able to really do anything to you, an easy fix would be just to have none standard issue not change the city 17 intro maps.

**Comment by Milkman68** [comment]
Wow, can't believe I didn't think to check this. Thanks for reporting, it'll be fixed in the next release.

**Comment by Milkman68** [comment]
Closing this issue as the next update is releasing with this bug fixed.
